export const DOUGHNUT_CHART = "doughnut_chart"
export const BAR_CHART = "bargraph_vertical"
export const HORIZONTAL_BAR_CHART = "bargraph_horizontal"
export const ATTACHMENT_TYPE_QUICKREPLY_TEXT = "quickReplyText"
export const ATTACHMENT_TYPE_QUICKREPLY_IMAGE = "quickImageText"
export const ATTACHMENT_TYPE_EXCEL = "excel"
export const FIRST_MESSAGE = "firstmessage"